-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 09:35:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id_role` INT NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statut` (
  `id_statut` INT NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_statut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `discord` VARCHAR(100) NULL,
  `role_id_role` INT NOT NULL,
  `statut_id_statut` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`),
  INDEX `fk_utilisateur_role1_idx` (`role_id_role` ASC) VISIBLE,
  INDEX `fk_utilisateur_statut1_idx` (`statut_id_statut` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_role1`
    FOREIGN KEY (`role_id_role`)
    REFERENCES `mydb`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_statut1`
    FOREIGN KEY (`statut_id_statut`)
    REFERENCES `mydb`.`statut` (`id_statut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distination` (
  `id_distination` INT NOT NULL,
  `nom` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_distination`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trajet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trajet` (
  `id_trajet` INT NOT NULL AUTO_INCREMENT,
  `lieux` VARCHAR(120) NOT NULL,
  `date` DATETIME NOT NULL,
  `commentaire` VARCHAR(255) NULL,
  `places` TINYINT(0) NOT NULL,
  `statut_id_statut` INT NOT NULL,
  `distination_id_distination` INT NOT NULL,
  PRIMARY KEY (`id_trajet`),
  INDEX `fk_trajet_statut1_idx` (`statut_id_statut` ASC) VISIBLE,
  INDEX `fk_trajet_distination1_idx` (`distination_id_distination` ASC) VISIBLE,
  CONSTRAINT `fk_trajet_statut1`
    FOREIGN KEY (`statut_id_statut`)
    REFERENCES `mydb`.`statut` (`id_statut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trajet_distination1`
    FOREIGN KEY (`distination_id_distination`)
    REFERENCES `mydb`.`distination` (`id_distination`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur_trajet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur_trajet` (
  `utilisateur_id_utilisateur` INT NOT NULL,
  `trajet_id_trajet` INT NOT NULL,
  PRIMARY KEY (`utilisateur_id_utilisateur`, `trajet_id_trajet`),
  INDEX `fk_utilisateur_trajet_trajet1_idx` (`trajet_id_trajet` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_trajet_utilisateur`
    FOREIGN KEY (`utilisateur_id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_trajet_trajet1`
    FOREIGN KEY (`trajet_id_trajet`)
    REFERENCES `mydb`.`trajet` (`id_trajet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bloque` (
  `utilisateur_id_utilisateur` INT NOT NULL,
  `utilisateur_id_utilisateur1` INT NOT NULL,
  PRIMARY KEY (`utilisateur_id_utilisateur`, `utilisateur_id_utilisateur1`),
  INDEX `fk_bloque_utilisateur2_idx` (`utilisateur_id_utilisateur1` ASC) VISIBLE,
  CONSTRAINT `fk_bloque_utilisateur1`
    FOREIGN KEY (`utilisateur_id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bloque_utilisateur2`
    FOREIGN KEY (`utilisateur_id_utilisateur1`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
